### PR TITLE
Added simple about page

### LINKED ISSUE #6: Define an about page?

### PR DESCRIPTION
**Pull request by davidn0rman**
Nothing fancy. Just an about page, a link to it from the home page, a back link to get back to the homepage, and some basic tests like the other pages.

Resolves #6 - I think...

### CODE REVIEW

**Comment by markgaze** [comment]
#### 📝Changed routes:


| [**/about**](https://sealwadding-blog-ifhufkzae-markgaze.vercel.app/about) | [**/**](https://sealwadding-blog-ifhufkzae-markgaze.vercel.app/) |
|:-:|:-:|
|<a href="https://sealwadding-blog-ifhufkzae-markgaze.vercel.app/about">Screenshot of /about</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/hKQOadxz3iP5k84pc8NT8qt3riChuiqhX-jYaMSTbIqxI3jEXCbl4vETxaUEzQ8kUm_ZYjDOYHScSloVKKdO8g.png">(view full size)</a> |<a href="https://sealwadding-blog-ifhufkzae-markgaze.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/79JxJZgwQKLsdqhbAjty4jVnIiqudGusDPmaWKJnF7Jw2VCFCDgBKsdRau96e-bvZ9OUFvHcrBQe3bGIVb-pew.png">(view full size)</a> |







Commit a8a1a1a8948de31fa46a89369b0033c4026927c3 (https://sealwadding-blog-ifhufkzae-markgaze.vercel.app).

**Comment by andrewbarnesweb** [comment]
I added my thoughts on this here https://github.com/sealwadding/blog/issues/5#issuecomment-842948044

Reckon it's overhead we could do without right now. But happy to proceed if we think we can add a decent page in the short term.

**Comment by davidn0rman** [comment]
> I added my thoughts on this here [#5 (comment)](https://github.com/sealwadding/blog/issues/5#issuecomment-842948044)
> 
> Reckon it's overhead we could do without right now. But happy to proceed if we think we can add a decent page in the short term.

Be worth having that on #6 - But as per [Slack](https://omega-13.slack.com/archives/C0223M3RYJE/p1621717298152400), sounds like we'll keep it for now and depending on how its fleshed out in design, we can take it from there. For now, gives us the building block at least.

**Comment by benmatselby** [comment]
Could the home and about be one in the same? And we scroll to sections? I agree we don't have a lot of content. The author page was more to give us a place to link to other authors not as a stand alone page. So this could all be merged.

**Comment by andrewbarnesweb** [comment]
I can't quite envisage having the about on the home page right now. It'd been designed in the short term to just list the recent blog posts and then we could move forward with enhancements. 

A page with distinct scrolling anchors would hit us with more to worry about I think. As we'd then need a hero area for the site, rather than just use the most recent post.

I think let's just get this merged in since Dave spent his Saturday eve on it, as it won't be much work to rejig or even remove things. And Dave and I can crack on with a design that everyone can focus on. I'll see if I can get some time to look at the home page today.

**Comment by andrewbarnesweb** [comment]
https://github.com/sealwadding/blog/issues/15#issuecomment-846524052

**Review by andrewbarnesweb — APPROVED** [review]

**Pull request merged**
